# .github/workflows/manual-update.yml
name: Actualización Manual de Localidad (Gemini Robot)

# 1. Disparador: Se activa cuando el dashboard llama al API (repository_dispatch)
# El tipo debe coincidir con la constante WORKFLOW_EVENT_TYPE en dashboard.html
on:
  repository_dispatch:
    types: [manual-update-city] 

jobs:
  run_generator_for_city:
    runs-on: ubuntu-latest
    
    # 2. Leer la ID de la localidad enviada por el dashboard
    env:
      TARGET_LOCALITY_ID: ${{ github.event.client_payload.locality_id }}

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependencias (requests es necesario para generator.py)
      run: pip install requests

    - name: Ejecutar Robot (Generator.py)
      run: |
        echo "Iniciando generación para localidad: $TARGET_LOCALITY_ID"
        
        # ⚠️ EJECUCIÓN CRÍTICA: Llama al script y pasa la ID como argumento
        python generator.py $TARGET_LOCALITY_ID
      env:
        # Clave secreta para Gemini, protegida en tu repo
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        
    - name: Commit de los archivos generados y actualizados
      run: |
        # Configurar Git con el bot de Actions
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # El script genera noticias_[id].json, lo agregamos y subimos
        git add noticias_*.json 
        git commit -m "Robot: Actualización forzada para $TARGET_LOCALITY_ID" || echo "No hay cambios para commit"
        git push
